### ISSUE TITLE
Problem in package installation

### ISSUE THREAD

**Issue by rafapereirabr** [wpgp/wpCPR#1]
Hi @bondarenkom. I'm getting the followring ERROR when trying to install `wpCPR` from a fresh session. Do you know what could be causing this?

Thanks in advance!

`devtools::install_github("wpgp/wpCPR")`

> Downloading GitHub repo wpgp/wpCPR@HEAD
> √  checking for file 'C:\Users\user\AppData\Local\Temp\Rtmpm0nrT3\remotes5c01f801661\wpgp-wpCPR-63d899f/DESCRIPTION' (505ms)
> -  preparing 'wpCPR':
> √  checking DESCRIPTION meta-information ... 
> -  checking for LF line-endings in source and make files and shell scripts
> -  checking for empty or unneeded directories
> -  building 'wpCPR_0.1.0.tar.gz'
>    
> Installing package into ‘C:/Users/user/Documents/R/win-library/4.0’
> (as ‘lib’ is unspecified)
> * installing *source* package 'wpCPR' ...
> ** using staged installation
> ** R
> ** byte-compile and prepare package for lazy loading
> **Error: (converted from warning) package 'sf' was built under R version 4.0.4**
> **Execution halted**
> **ERROR: lazy loading failed for package 'wpCPR'**
> * removing 'C:/Users/user/Documents/R/win-library/4.0/wpCPR'
> Error: Failed to install 'wpCPR' from GitHub:
>   (converted from warning) installation of package ‘C:/Users/user/AppData/Local/Temp/Rtmpm0nrT3/file5c01d854a03/wpCPR_0.1.0.tar.gz’ had non-zero exit status
> 

Here is my session info

> R version 4.0.2 (2020-06-22)
> Platform: x86_64-w64-mingw32/x64 (64-bit)
> Running under: Windows 10 x64 (build 19042)
> 
> Matrix products: default
> 
> locale:
> [1] LC_COLLATE=English_United States.1252  LC_CTYPE=English_United States.1252   
> [3] LC_MONETARY=English_United States.1252 LC_NUMERIC=C                          
> [5] LC_TIME=English_United States.1252    
> 
> attached base packages:
> [1] stats     graphics  grDevices utils     datasets  methods   base     
> 
> loaded via a namespace (and not attached):
> [1] compiler_4.0.2 tools_4.0.2

**Comment by bondarenkom** [comment]
Hi,

It looks like some mismatch between versions of the installed package. I could not reproduce this error. 
Please try a work around by ignoring the warning. Please set the environmental variable with R_REMOTES_NO_ERRORS_FROM_WARNINGS="true"

```
Sys.setenv(R_REMOTES_NO_ERRORS_FROM_WARNINGS="true")
devtools::install_github("wpgp/wpCPR")
```

**Comment by bondarenkom** [comment]
Hi

**Comment by bondarenkom** [comment]
Hi Rafael,
Thanks to @doug-leasure who updated the package so it should work now for R version 4.
Please try to install the package one more time.

**Comment by rafapereirabr** [comment]
Thank you, guys. I've tried installing again and got the same error. It worked well after I ran `Sys.setenv(R_REMOTES_NO_ERRORS_FROM_WARNINGS="true")` , though. Thanks.
